version: "3.3"

services:
  mysqldb:
    image: 'mysql:latest'
    restart: unless-stopped
    env_file: ./.env
    environment:      
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  app1:
    container_name: dockerfile_angular

    ports:
      - '4200:80'
    image: 46416514/dev-ops-project-app1
        
   
    
    restart: always
    depends_on:
      - app
volumes:
  db:
  crud-tuto-front: